; =========================
; Common
; =========================
[common]
lib_deps =
    sandeepmistry/LoRa @ ^0.7.0
    bblanchon/ArduinoJson @ ^6.21.3
monitor_speed = 115200

; =========================
; Sender Node
; =========================
[env:nodeSender]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = ${common.lib_deps}
monitor_speed = ${common.monitor_speed}
build_src_filter =
    -<*>
    +<nodeSender/>
build_flags =
    -D ROLE_SENDER
    -D DEVICE_ID=\"TENS-01\"

; =========================
; Receiver Node
; =========================
[env:nodeReceiver]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = ${common.lib_deps}
monitor_speed = ${common.monitor_speed}
build_src_filter =
    -<*>
    +<nodeReceiver/>
build_flags =
    -D ROLE_RECEIVER
    -D DEVICE_ID=\"GATEWAY-01\"

; =========================
; Test Node
; =========================
[env:nodeTest]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = ${common.lib_deps}
monitor_speed = ${common.monitor_speed}
build_src_filter =
    -<*>
    +<nodeTest/>
build_flags =
    -D ROLE_TEST
    -D DEVICE_ID=\"TEST-01\"
    -D DEBUG_MODE